spring:
  application:
    name: jchat-be
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

server:
  port: 8080